---

- name: JAVA | Installation
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ java_package }}"

- name: JAVA | Configure environment
  lineinfile:
    path: /etc/environment
    line: "JAVA_HOME={{ java_home }}"
    state: present
